### ISSUE TITLE
Numpy 1.12.0 bug causes unit test failure in bottleneck

### ISSUE THREAD

**Issue by toobaz** [kwgoodman/bottleneck#160] opened 2017-01-16 22:09 UTC
I ask forgiveness in advance for having no idea of whether this is an upstream problem or a packaging problem... I don't have time now to investigate (and actually tests run fine in my - partially out of date - debian testing). But maybe the output of those tests sounds familiar to you...

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851613

**Comment by kwgoodman** [comment] 2017-01-16 22:47
Hey there!

Looks like numpy on his system is returning 2 instead of inf for:
```
In [1]: a = np.array([4, np.nan, np.nan, np.inf], dtype=np.float32)
In [2]: bn.nanmedian(a)
Out[2]: inf
In [3]: np.nanmedian(a)
Out[3]: inf  # <--- his system appears to return 2 here
```

**Comment by ghisvail** [comment] 2017-01-16 23:11
I am using numpy 1.12.0rc2. You think this is a regression from the latest version?

**Comment by kwgoodman** [comment] 2017-01-16 23:12
What's the output when you run the example I provided?

**Comment by ghisvail** [comment] 2017-01-16 23:31
```python
>>> import numpy as np
>>> import bottleneck as bn
>>> a = np.array([4, np.nan, np.nan, np.inf], dtype=np.float32)
>>> bn.nanmedian(a)
inf
>>> np.nanmedian(a)
inf
>>> print(np.__version__)
1.12.0rc2
```

**Comment by kwgoodman** [comment] 2017-01-16 23:35
Hmm...what about bn.test() output?

**Comment by ghisvail** [comment] 2017-01-16 23:38
```
>>> import bottleneck as bn
>>> bn.test()
Running unit tests for bottleneck
NumPy version 1.12.0rc2
NumPy relaxed strides checking option: True
NumPy is installed in /usr/lib/python3/dist-packages/numpy
Python version 3.5.3rc1 (default, Jan  3 2017, 04:40:57) [GCC 6.3.0 20161229]
nose version 1.3.7
.................................................................F....................................................F..................................................
======================================================================
FAIL: test move functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 729, in chk_same_position
    assert_array_equal(x_id, y_id)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 871, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 8.333333333333329%)
 x: array([[ True,  True, False, False, False, False],
       [False, False, False, False, False,  True]], dtype=bool)
 y: array([[ True,  True, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/bottleneck/tests/move_test.py", line 42, in unit_maker
    aaae(actual, desired, decimal, err_msg)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 979, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 761, in assert_array_compare
    chk_same_position(x == +inf, y == +inf, hasval='+inf')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

func move_median | window 4 | min_count 1 | input a50 (float32) | shape (2, 6) | axis -1 | order C

Input array:
[[ inf   7. -inf  -9. -10.  nan]
 [ nan   5.   4.  nan  nan  inf]]

x and y +inf location mismatch:
 x: array([[  inf,   inf,   7. ,  -1. ,  -9.5, -10. ],
       [  nan,   5. ,   4.5,   4.5,   4.5,   inf]], dtype=float32)
 y: array([[  inf,   inf,   7. ,  -1. ,  -9.5, -10. ],
       [  nan,   5. ,   4.5,   4.5,   4.5,   2. ]], dtype=float32)

======================================================================
FAIL: test reduce functions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 729, in chk_same_position
    assert_array_equal(x_id, y_id)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 871, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 796, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 33.33333333333333%)
 x: array([False, False,  True], dtype=bool)
 y: array([False, False, False], dtype=bool)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/bottleneck/tests/reduce_test.py", line 63, in unit_maker
    assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 979, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 761, in assert_array_compare
    chk_same_position(x == +inf, y == +inf, hasval='+inf')
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 735, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 5 decimals

func nanmedian | input a61 (float32) | shape (3, 4) | axis -1 | order C

Input array:
[[ inf   7. -inf  -9.]
 [-10.  nan  nan   5.]
 [  4.  nan  nan  inf]]

x and y +inf location mismatch:
 x: array([-1. , -2.5,  inf], dtype=float32)
 y: array([-1. , -2.5,  2. ], dtype=float32)

----------------------------------------------------------------------
Ran 169 tests in 47.258s

FAILED (failures=2)
<nose.result.TextTestResult run=169 errors=0 failures=2>
```

**Comment by ghisvail** [comment] 2017-01-16 23:44
FYI, same outcome if I use a venv instead of the system packages

**Comment by ghisvail** [comment] 2017-01-16 23:46
And it tests fine if I downgrade numpy to 1.11.3 in the venv. So all this points to a regression in `numpy` from 1.11.x to 1.12.

**Comment by kwgoodman** [comment] 2017-01-16 23:51
How about:
```
In [1]: inf = np.inf
In [2]: nan = np.nan
In [3]: a = [[inf, 7, -inf, -9]]
In [4]: a.append([-10, nan, nan, 5])
In [5]: a.append([4, nan, nan, inf])
In [6]: a = np.array(a, dtype=np.float32)
In [7]: a
Out[7]: 
array([[ inf,   7., -inf,  -9.],
       [-10.,  nan,  nan,   5.],
       [  4.,  nan,  nan,  inf]], dtype=float32)
In [8]: bn.nanmedian(a, axis=-1)
Out[8]: array([-1. , -2.5,  inf], dtype=float32)
In [9]: bn.slow.nanmedian(a, axis=-1)
Out[9]: array([-1. , -2.5,  inf], dtype=float32)
In [10]: np.nanmedian(a, axis=-1)
Out[10]: array([-1. , -2.5,  inf], dtype=float32)
```

**Comment by ghisvail** [comment] 2017-01-16 23:54
Yep, not what you expected:
```
>>> bn.nanmedian(a, axis=-1)
array([-1. , -2.5,  inf], dtype=float32)
>>> bn.slow.nanmedian(a, axis=-1)
array([-1. , -2.5,  2. ], dtype=float32)
>>> np.nanmedian(a, axis=-1)
array([-1. , -2.5,  2. ], dtype=float32)
```

**Comment by ghisvail** [comment] 2017-01-16 23:56
Anyway, I have shown that the issue was not specific to Debian and that it could be reproduced in a venv. You just need to instantiate 2 venvs, one will have the recently released numpy `1.12.0` and the other can be downgraded to `1.11.3`.

**Comment by kwgoodman** [comment] 2017-01-16 23:58
OK, the problem is in numpy (as you already mentioned). Perhaps you can report it if it hasn't already been reported.

**Comment by ghisvail** [comment] 2017-01-17 00:09
Could you paste the relevant minimal reproducible code for the issue that I should forward to the Numpy folks, please. Thanks.

**Comment by kwgoodman** [comment] 2017-01-17 00:11
Any example that return 2 instead of inf would be good

**Comment by shoyer** [comment] 2017-01-17 00:28
Just a note -- the test case that failed in xarray when bottleneck was used involves an array with no `inf` values. And in that case, the bad values looked to be coming from bottleneck, not numpy. So something else may also be going wrong.

I *think* something like this script may suffice to reproduce it:
```python
import numpy as np
import bottleneck as bn
x = np.random.randn(10, 20)
np.testing.assert_array_almost_equal(x[:, 9:10].sum(), bn.nansum(x[:, 9:10]))
```

See https://github.com/pydata/xarray/issues/1208#issuecomment-272763117 for more details.

**Comment by kwgoodman** [comment] 2017-01-17 01:07
That runs fine for me:
```
In [1]: import numpy as np
   ...: import bottleneck as bn
   ...: x = np.random.randn(10, 20)
   ...: np.testing.assert_array_almost_equal(x[:, 9:10].sum(), bn.nansum(x[:, 9:10]))
   ...: 
   ...: 
```

**Comment by kwgoodman** [comment] 2017-01-17 01:09
@ghisvail good idea to have a minimal example. You might want to make sure you get the wrong numpy output even when bottleneck is not called at all. Could be, for example, that bottleneck is messing up the input array.

**Comment by ghisvail** [comment] 2017-01-17 08:46
> That runs fine for me [...]

Me too.

**Comment by ghisvail** [comment] 2017-01-17 10:10
> good idea to have a minimal example

There you go:
```python
import numpy as np
inf = np.inf
nan = np.nan
a = np.array([[inf, 7, -inf, -9],
              [-10, nan, nan, 5],
              [4, nan, nan, inf]],
              dtype=np.float32)
print(np.nanmedian(a, axis=-1))
print(np.nanmedian(a[0]))
print(np.nanmedian(a[1]))
print(np.nanmedian(a[2]))
```

numpy-1.11.x:
```
[-1.  -2.5  inf]
-1.0
-2.5
inf
```

numpy-1.12:
```
[-1.  -2.5  2. ]
-1.0
-2.5
inf
```

Forwarding it to Numpy...

**Comment by kwgoodman** [comment] 2017-01-17 15:58
@ghisvail Both of the bottleneck unit test failures (nanmedian and move_median) you saw are due to the same numpy bug. Are there any other issues? Or are we done?

**Comment by ghisvail** [comment] 2017-01-17 16:21
Looks like it should be fixed by https://github.com/numpy/numpy/pull/8489.

**Comment by kwgoodman** [comment] 2017-01-17 16:25
Then we're done. Good working with you.

**Closed by kwgoodman** 2017-01-17 16:25 UTC
